[package]
name = "wezterm-config-derive"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/tw93/Kaku"
description = "derive config metadata"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
